services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shopsphere
      POSTGRES_USER: shopsphere
      POSTGRES_PASSWORD: shopsphere
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopsphere -d shopsphere"]
      interval: 5s
      retries: 20

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shopsphere
      SPRING_DATASOURCE_USERNAME: shopsphere
      SPRING_DATASOURCE_PASSWORD: shopsphere
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  dbdata:
